server.port=8080

# Rutas hacia microservicios (Spring Cloud Gateway)
spring.cloud.gateway.server.webflux.routes[0].id=servicio-pacientes
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/pacientes/**

spring.cloud.gateway.server.webflux.routes[1].id=servicio-lista-espera
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/listas-espera/**

spring.cloud.gateway.server.webflux.routes[2].id=servicio-lista-espera-citas
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/citas/**

spring.cloud.gateway.server.webflux.routes[3].id=servicio-reasignacion
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/reasignaciones/**

spring.cloud.gateway.server.webflux.routes[4].id=servicio-notificaciones
spring.cloud.gateway.server.webflux.routes[4].uri=http://localhost:8084
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/notificaciones/**

# JWT
jwt.secret=cmVkbm9ydGUtand0LXNlY3JldC1rZXktMjAyNi1tdXktc2VndXJhLXktbGFyZ2E=
jwt.expiration=86400000

# Contrasena por defecto para clientes
app.cliente.password=rednorte2026

# URLs internas para los clientes BFF (server-to-server, sin pasar por el gateway)
services.pacientes.url=http://localhost:8081
services.lista-espera.url=http://localhost:8082
services.reasignacion.url=http://localhost:8083
services.notificaciones.url=http://localhost:8084

# Swagger / SpringDoc
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config
springdoc.swagger-ui.url=/v3/api-docs
springdoc.webjars.prefix=
