server.port=8083

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5435/reasignacion_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:postgres}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASS:guest}

# URL interna de servicio-lista-espera (server-to-server, sin pasar por el gateway)
services.lista-espera.url=${SERVICIO_LISTA_ESPERA_URL:http://localhost:8082}